### ISSUE TITLE
LLVM_EXTERNAL_LIT set to /build/llvm/src/llvm-10.0.1.src/utils/lit/lit.py, but the path does not exist.

### ISSUE THREAD

**Issue by anusman-maximus** [leaningtech/cheerp-meta#101]
I am running Arch Linux.
**/opt/cheerp/bin/clang++ --version** ` clang version 9.0.0 Target: cheerp-leaningtech-webbrowser-wasm InstalledDir: /opt/cheerp/bin`
**cmake --version** `cmake version 3.18.3`
**Python --version** `Python 3.8.5`
**node --version**  `v14.13.0`

I have **compile everything** -> attempted to **run hello.cpp** -> **googled** for about an hour, to no avail -> **removed everything** -> re-**downloaded** -> re-**compiled** -> re **run hello.cpp**
and _still_ I get the following error:
```
sudo /opt/cheerp/bin/clang++ -target cheerp hello.cpp -o hello.js
/opt/cheerp/bin/llvm-link: libstdlibs.bc: error: Could not open input file: No such file or directory
/opt/cheerp/bin/llvm-link: error:  loading file 'libstdlibs.bc'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```
Output of _make -C stdlibs install_asmjs INSTALL_PREFIX=/opt/cheerp CHEERP_PREFIX=/opt/cheerp_
```
make: Entering directory '/home/peppe/Documents/cheerp/cheerp-libs/stdlibs'
make: *** No rule to make target '/opt/cheerp/lib/asmjs/libc.bc', needed by 'asmjs/libstdlibs.full.bc'.  Stop.
make: Leaving directory '/home/peppe/Documents/cheerp/cheerp-libs/stdlibs
```

Also when I try to Build asm.js/wasm version for C doing `../configure --host=cheerp-asmjs --with-cxx-headers=$CHEERP_SRC/cheerp-libcxx/include --prefix=/opt/cheerp --enable-newlib-io-long-long --enable-newlib-iconv --enable-newlib-iconv-encodings=utf-16,utf-8,ucs_2 --enable-newlib-mb --enable-newlib-nano-formatted-io`
results in the following
`bfd plugin: LLVM gold plugin has failed to create LTO module: Invalid value (Producer: 'LLVM9.0.0svn' Reader: 'LLVM 10.0.1')`

 Any ideas on how to fix this?

**Comment by alexp-sssup** [comment]
We recommend Linux to use pre-made packages for Debian/Ubuntu, the build system of the newlib library is not as robust as we would like. We plan to replace the library with a better implementation at some point. The problem you need to solve is the newlib build, without that you cannot build the cheerp-libs package which the compiler needs to build any executable.

I think some component from you local LLVM installation is being mistakenly used during the newlib build. Cheerp is based on LLVM/clang 9, and since the message mentions LLVM 10.0.1 I suspect that comes from your system. A possible workaround would be to build Cheerp in a clean VM or chroot to avoid unexpected interactions with system components.

**Comment by anusman-maximus** [comment]
@alexp-sssup I will try to do that! Also I fully understand that you recommend the pre-made packages, but they are only available for Debian/Ubuntu. Arch Linux is also a widely used Linux derivative and should be considered to be added to the list of pre-build packages for Linux. Thanks!
