### ISSUE TITLE
clang-9: error: unable to execute command: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Yongli0510** [leaningtech/cheerp-meta#104]
I want to complie my test.cc into wasm type using the 
` /opt/cheerp/bin/clang++ -target cheerp-wasm test.cc -std=c++1z -O3` 
command, but I meet this problem: `clang-9: error: unable to execute command: Segmentation fault (core dumped)`
![image](https://user-images.githubusercontent.com/37619159/116982053-ecd33c00-acfa-11eb-8301-01b5a6866c11.png)
Anyone knows about this? Thanks.

**Comment by carlopi** [comment]
Hi @Yongli0510, this is clearly not supposed to happen. Could you share the test.cc file you are compiling, so I can then reproduce and fix the problem?

**Comment by Yongli0510** [comment]
> Hi @Yongli0510, this is clearly not supposed to happen. Could you share the test.cc file you are compiling, so I can then reproduce and fix the problem?

@carlopi 
Thanks for attention! The test.cc is a filter I'm writing for envoy and I want to compile it to test.wasm.
Because the file format limit of github, I have to rename the test.cc to test.txt, so you maybe change it to test.cc yourself:
[test.txt](https://github.com/leaningtech/cheerp-meta/files/6420613/test.txt)
Thanks again!

**Comment by carlopi** [comment]
Are you by any chance compiling [this project](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk) example?
This is meant to work with the Emscripten toolchain, since it uses toolchain-specific attributes.
Adding the right Cheerp's attributes (eg. `[[cheerp::jsexport]]` instead of `__attribute__((visibility("default")))`) it should be possible to compile this with Cheerp, but I haven't tried (yet).

**Comment by carlopi** [comment]
The problem is now solved on master, there were some problems related to indirect tagging of lambdas that has been properly solved.

The codebase now compiles, but as mentioned it will require to be tagged with the proper attributes (mainly [[cheerp::jsexport]] to force functions to be externally visible).

Thanks for signaling the issue!
