### ISSUE TITLE
All links are broken

### ISSUE THREAD

**Issue by paulo-coutinho** [leaningtech/cheerp-meta#111]
Hi,

All links here are broken:

![image](https://user-images.githubusercontent.com/395096/141396189-c189be3e-cd9f-4830-ba1b-a191a5b95d3c.png)

**Comment by carlopi** [comment]
Thanks for noticing this out, the documentation has been moved here: [https://docs.leaningtech.com/cheerp/](https://docs.leaningtech.com/cheerp/), and there the links should be working as intended, but I have to fix them in the cheerp-meta repo.

**Comment by carlopi** [comment]
Hi, in the end the fix was obvious, see https://github.com/leaningtech/cheerp-meta/commit/3c94ef0397279264877ab614c50a92c2ed1c30e6.

I will also to the other md's a header informing that the internal links are not relatives. This is not ideal, but the two main concerns where low overhead + search-ability is better served as GitHub's page (pointing to https://docs.leaningtech.com).

Thanks again!
