### ISSUE TITLE
Feature request: JS Promise Integration

### ISSUE THREAD

**Issue by isaackwan** [leaningtech/cheerp-meta#143]
Any plans to add support for https://github.com/WebAssembly/js-promise-integration/ please?

**Comment by fgmccabe** [comment]
1. JSPI is not 'obligatory': if you have the means to manipulate Promise objects in wasm then 'go for it'. However, this will be a compile-time/coding-time choice: wrapping exports/imports fixes the semantics for those functions.
2. JSPI is not intended to be the complete story for JS integration: it is specific in nature.
3. I find comment #3 to be difficult to comprehend. It is, by design, a tightly focused proposal that does not preclude other proposals.

Note that accessing Promise objects from wasm is not likely to be 'smooth' for the foreseeable future.

Note also that there is additional work around bringing stack switching capabilities to wasm. Some of your concerns may be addressed or amplified by that work. Core stack switching is much earlier on in the process at the moment.

**Comment by yuri91** [comment]
@fgmccabe The main issue of this proposal in the context of Cheerp is that (afaik) it does not allow to suspend a stack frame that contains JS functions.

It is understandable why (you could use this to wrap js functions and make them suspendable, but the JS committee does not like that), but in Cheerp it is very common to have mixed stack frames, because you can tag your C++ functions so that they are compiled into JS or Wasm.

The result would be difficult to debug runtime errors that appear if you change the implementation details of some function. And detecting these situation at compile time is not really feasible.

**Comment by fgmccabe** [comment]
Yes, well, we are prohibited from allowing JS frames to be captured in this way. The principal reason is that that would change the semantics of JS itself. And, as you note, it does introduce some 'glitches'.
