### ISSUE TITLE
How can I complie c libs with cheerp

### ISSUE THREAD

**Issue by langhuihui** [leaningtech/cheerp-meta#36]
`clang -target cheerp *****.c -o *****.bc`
but there are many errors
such as 
+ C:\cheerp\bin\clang -std=c11 -O3 -c -target cheerp -I..\include -I..\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (In file included from bits.c:41::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
./os_support.h:73:19: error: Cheerp: Memory operations require the actual type of the pointers. Pass the typed pointers instead of a generic void*
   return realloc(ptr, size);

**Comment by langhuihui** [comment]
I know what's wrong now. cheerp is not support all c code.

**Comment by alexp-sssup** [comment]
On the Web platform there are no bytes under an object, so extra type-safety must be ensured by user code. In the specific case I think that the code tries to use memcpy/memmove/memset on void*, that can't be supported because the compiler would not know what is the real type of the memory and such information is required to generate proper, type-safe memcpy code.

**Comment by langhuihui** [comment]
So I can't use many other c/c++ libs. However emscripten can do such things. I hope cheerp can be more useful someday.

**Comment by alexp-sssup** [comment]
In our experience most C++ code works with minimal changes. C code is often more difficult to compile though. The enhanced type safety that Cheerp requires is the price to pay for dynamic memory allocations, on the other end Emscripten can support raw memcpy since all memory is mapped into a huge typed arrays. We are currently developing a new allocation model which is more compatible with C libraries while still allowing dynamic allocations, but it is not mature enough for release now.

**Comment by langhuihui** [comment]
If Cheerp can call other libs,it will be much more powerful than Emscripten.

**Comment by jjzazuet** [comment]
+1, thanks!

**Comment by alexp-sssup** [comment]
With WebAssembly, as available in version 2.0RC1, legacy code should be able to compile without any problem. You can enable WebAssembly mode using the ```-cheerp-mode=wasm``` command line option. For more information see https://github.com/leaningtech/cheerp-meta/wiki/WebAssembly-output-(wasm-or-wast-mode) and https://github.com/leaningtech/cheerp-meta/wiki/Cheerp-Tutorial:-Mixed-mode-C---to-WebAssembly-and-JavaScript
