### ISSUE TITLE
Add Support CLion IDE and Debugger

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#43]
Please add Support CLion IDE and Debugger.

1) I mean, I want to press the "run" in the top of the IDE, and the application must compile and run in the browser.

2) I want to put a breakpoint in IDE, click debug, and make it run in a browser, and the browser used javascript debugger and sourcemaps, all automatically broadcast from the browser debugger, to the embedded IDE C++ debugger, to debug code without leaving from IDE.

3) I want to have Webpack support and auto incremental compile, and hot module reload, without reloading the entire page.

It's much more important than adding new features and innovations into Cheerp. If you do not add support infrastructures, all Cheerp features do not have sense.

All languages are broadcast in javascript, are integrated into the existing javascript infrastructure. I think C++ should not be an exception.

It sounds like magic, but it's computers, they all virtually, so anything is possible. I am willing to even help you to realize all this. =)

![image](https://cloud.githubusercontent.com/assets/19378179/22392377/5d01e53a-e509-11e6-8100-b2b8cd28bcaa.png)

![image](https://cloud.githubusercontent.com/assets/19378179/22392538/77c5d514-e50b-11e6-98f7-2a67e79f5d54.png)

![image](https://cloud.githubusercontent.com/assets/19378179/22393743/6ce8114e-e51e-11e6-9cc2-a341313fde41.png)

etc.

**Comment by alexp-sssup** [comment]
In general there are too many IDEs to support all of them. Integrating Cheerp into systems with existing C++ support should be simple since Cheerp provides gcc/clang compatible command line options. You may also probably want to take a look at debugging support using SourceMaps on our Wiki https://github.com/leaningtech/cheerp-meta/wiki/In-browser-debugging-with-Source-Maps. We do not plan to provide any integrated support for specific IDEs at the moment.
