### ISSUE TITLE
Add built-in "Google closure-compiler" in Advanced mode support

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#44]
Now, this code:

```c++
#include <cheerp/client.h>
using namespace client;

int webMain() {
    alert("111 + 333");
    return 0;
}
```

With -O3 flag compile to this:

```javascript
"use strict";
/*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
var aSlot = null;
var oSlot = 0;
var nullArray = [null];
var nullObj = {d: nullArray, o: 0};
function k() {
	var a = "111 + 333";
	alert(a);
	return 0 >> 0;
}
function j(m, n) {
	var label = 0;
	var a = String();
	var b = (m[n >> 0 >> 0] & 255);
	if (!(((b & 255) === 0))) {
		var c = 0;
		while (1) {
			var l = String.fromCharCode(((b << 24) >> 24) >> 0);
			var a = a.concat(l);
			var c = ((c >> 0) + (1 >> 0) >> 0);
			var b = (m[(n >> 0) + (c >> 0) >> 0] & 255);
			if (((b & 255) === 0)) {
				break;
			}
		}
	}
	return String(a);
}
var d = new Uint8Array([49, 49, 49, 32, 43, 32, 51, 51, 51, 0]);
k();
```

But Google closure compiler in anvansed mode minify this code to this:

![image](https://cloud.githubusercontent.com/assets/19378179/22393964/1b5524c4-e524-11e6-95cc-f233aa015641.png)

I can not just translate code with "closure compiler" manually. 
Since advanced mode requires writing code in a special way.
And it is the task of the Cheerp.

**Comment by alexp-sssup** [comment]
In this toy example there is a significant advantage in using the closure compiler, but in our experiments on larger code bases and real world programs the advantage is much less. We usually see a 15%-20% improvement when compiling with closure compiler compared to code minimized only by Cheerp.

We acknowledge that we could do better and we are currently working to improve the minimizer. Using the closure compiler directly is a bad idea, since it can mess up the carefully optimized code that we generate. When generating code we take into account a lot of details on how modern JS engines generate native code from JavaScript to maximize performance and we have observed that closure compiler can actually make Cheerp-ed code slower.

As an example Cheerp tries to minimize the amount of local variables by recycling them, but it does so while exploiting the internal type tracking of JS engines to avoid using the not efficient boxed representation of values. Closure compiler will instead collapse variables without accounting for this type information and the generated code will be of lower quality/lower performance at runtime.

As a final note, taken all together Cheerp minimizes code effectively. The generated code is usually smaller than what emscripten does on similar code and it is often comparable to the size of native code for x86 or ARM.
