### ISSUE TITLE
What about Rust support?

### ISSUE THREAD

**Issue by LukasKalbertodt** [leaningtech/cheerp-meta#5]
Hi there!

I'm wondering how difficult it would be to support [Rust](https://rust-lang.org). The Rust compiler uses LLVM and can easily emit LLVM IR. Have you been thinking about that?

I'm certainly interested in it. What would be necessary to support Rust? Probably:
- a port of the Rust standard library (like `cheerp-libcxx` is for the C++ std)
- a port of `cheerp-utils` into Rust
- some modifications to your compiler
- more?

I'd be happy to receive any information about this :)

**Comment by alexp-sssup** [comment]
This project would be interesting but not trivial. To generate code compatible with the object model of the Web, the compiler must be very careful is doing type safe transformations and generation of LLVM IR. This project would most probably require work on the rust frontend side to make sure that generated code is type safe enough for the Web platform.

**Comment by LukasKalbertodt** [comment]
Could you elaborate on what "type safe transformations" means? Or is there a documentation about this topic?

**Comment by alexp-sssup** [comment]
The job of an optimizing compiler such as LLVM is to transform input code into an output which has the same semantics but run faster. This happens through a large number of different transformations on input code. The input LLVM IR code may be fully type safe, but one of those transformations may break type safety by assuming that the target architecture is byte addressable. For example consider the following code:

```c++
class A
{
    int data;
};
....
A a;
a.data = 2;
````

When assigning the property ```data``` clang would generate code like this LLVM pseudo code

```
getelementptr A* %a, i32 0, i32 0;
```

This means: "Get a pointer to the first element of an object of type A". This code is fully type safe and works flawlessly an both byte addressable and object addressable architectures (like Cheerp)

A problem arise when a poorly written optimization does the following transformation:

```
getelementptr A* %a, i32 0, i32 0; -> bitcast A* to i32*;
```

The new code means take the pointer to A and change the type to pointer to integer. This is not type safe but it does work on byte addressable architecture because indeed the pointer to ```a``` and the pointer to the first element of ```a``` have the same numeric value. There are some optimizations in LLVM that behave like this.

This would not be most probably a problem in getting rust the work, as the Cheerp LLVM code has been modified to avoid all instances of type unsafe code transformation. But successful compilation does also require that the code is type safe to begin with, this is why I said that work would be required on the rust fronted to make sure that generated LLVM code is fully type safe.

**Comment by LukasKalbertodt** [comment]
Ok thanks for the explanation. So the problem is to make sure the Rust compiler emits type safe LLVM code to begin with. Then this unoptimized LLVM code would be passed to your cheerp tool.

Sadly, I'm not familiar with the `rustc` backend (not implying that I know much about the other parts). I'll try to ask someone, who knows stuff about that :)

**Comment by Kimundi** [comment]
Hi, I'm not deeply familiar with the workings of llvm, but reading that explanation I'm wondering about one thing: Doesn't llvm plan to [remove the type information from pointers?](http://llvm.org/devmtg/2015-10/slides/Blaikie-OpaquePointerTypes.pdf)

**Comment by alexp-sssup** [comment]
It seems that pointer type data will be moved from the pointers themselves to the instructions using them, such as load and getelementptr. To a large extend it should not affect the Cheerp architecture.

**Comment by alexp-sssup** [comment]
This goes outside the scope of the project. Closing.
