### ISSUE TITLE
How i can create javascript projection of existing C++ object?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#53]
```c++
class [[cheerp::jsexport]] Cat {
public:
    int age;
    Cat(int age) : age(age) {}
};


int webMain() {
    Cat *cat = new Cat(10); // create C++ object
    
    Object *catObj = new Object(cat); // wrap it to javascript object
    window._set("cat", catObj); // set it to window "cat" propperty
    return 0;
}
```

in javascript:
```javascript
cat.age // 10
```

How can I make something like that? Or I can not? So let's figure out how to implement these things. This is critical for my project, I think not only for my project.

**Comment by alexp-sssup** [comment]
This is currently unsupported but it will be possible in the future with some limitations.

**Comment by uMaxmaxmaximus** [comment]
I write polyfill:

```c++
namespace client {
    void setProto(JSObject *obj, const String &className);
}

class [[cheerp::jsexport]] Cat {

  Cat* toJS(){
    setProto(this, "Cat");
    return this;
  }

}
```


javascript func
```javascript

function setProto(obj, className) {
	var Class = eval(className); // get class by name
	if (Object.getPrototypeOf(obj) !== Class.prototype) {
		Object.setPrototypeOf(obj, Class.prototype);
	}
}

```

**Comment by cncmd** [comment]
First of all, you should determine the type of your program. In the concept of cheerp, there is no support for the emergence of dynamic fields, because it is not conducive to pre-derivation type optimization.
If you want to use js objects, define a class mapping under the client namespace before using it.

```
namespace client {
		class ManiFest {
		public:
		int get_endList();
		int get_allowCache();
		int get_targetDuration();
		int get_mediaSequence();
		int get_discontinuitySequence();
		Array * get_segments();
		Array * get_discontinuityStarts();
		void set_length(long int);
	};
}

```
Getting operations use get_method, cheerp automatically maps the dynamic attributes of JS into an inline method, and obtains them through pointers of objects.

When we use it like  this:
ManiFest * m = XXX(); 
m->get_allowCache() /// m.allowCache

We can use the set_method to set object attributes. The same like tthis.
m->set_length(0);   /// m.length = 0

This way the compiler knows when to optimize our code and how to interweave the smallest memory model throughout the context and lifecycle.


by 钟元 agent.zy@aliyun.com

**Comment by carlopi** [comment]
Hi @uMaxmaxmaximus, I am not sure what are the requirement of your project, but I believe this to be doable with the current capabilities of [[cheerp::jsexport]]: https://docs.leaningtech.com/cheerp/JSExport-attribute.html.

JsExported objects could be created both by C++ code and JavaScript code.
See for example this test: https://github.com/leaningtech/cheerp-utils/blob/master/tests/unit/jsexport/factory.cpp.

Passing JS-generated object to JS-generated objects could then be done via wrappers, like:
```
struct SomeClass
{
     // other method & members
     void cloneInto(SomeClass* someObject)
     {
            someObject->a = a;
            someObject->b = b;
     }
};
```
Then the only needed thing would be obtaining the relevant pointer from JS-world, and calling cloneInto. Depending on your exact needs the interface might have to be slightly different, but this should be workable.

**Comment by carlopi** [comment]
Please do reopen / or contact us on gitter (https://gitter.im/leaningtech/cheerp) to follow up should this not be workable.
